var minify = require('html-minifier').minify;
//var content = '<p title="blah" id="" id="moo" id="moo">  foo   </p> <h1> hi <!-- hi -->';
var content = '<html><head><title>Page Title</title></head><body><h1>This is a Heading</h1><p>This is a paragraph.</p></body></html>'
var result = minify(content, {
collapseWhitespace : true,
removeComments: true,
removeEmptyAttributes: true,
removeEmptyElements: true,

removeRedundantAttributes: true,
sortAttributes: true,
sortClassName: true,
removeComments: true,
minifyCSS: true,
minifyJS: true,
caseSensitive: true,
collapseInlineTagWhitespace: true,
keepClosingSlash: true,
includeAutoGeneratedTags: true
});
console.log(result);