var express=require('express');
var bodyParser = require('body-parser');
var minify = require('html-minifier').minify;
var app=express();
var port_no = 3000;

app.use(bodyParser.json() );       // to support JSON-encoded bodies
app.use(bodyParser.urlencoded({     // to support URL-encoded bodies
  extended: true
}));

app.use(express.static(__dirname + '/static'));

app.get('/',function(req,res){
	res.sendFile( __dirname + "/" + 'index.html');
});

app.post('/compress',function(req,res){
	console.log(req.body);
	
var content = req.body.data;
var result = minify(content, {
	collapseWhitespace : true,
	removeComments: true,
	removeEmptyAttributes: true,
	removeEmptyElements: true,
	removeRedundantAttributes: true,
	sortAttributes: true,
	sortClassName: true,
	removeComments: true,
	minifyCSS: true,
	minifyJS: true,
	caseSensitive: true,
	collapseInlineTagWhitespace: true,
	keepClosingSlash: true,
includeAutoGeneratedTags: true
});
console.log(result);
	
	var response = {};
	response.status = true;
	response.data = result;
	res.send(response);
});

app.listen(port_no, function(){
	console.log("Express Started on Port "+port_no);
});