var express=require('express');
var bodyParser = require('body-parser');
var minify = require('html-minifier').minify;
var app=express();
var port_no = 3000;

app.use(bodyParser.json() );       // to support JSON-encoded bodies
app.use(bodyParser.urlencoded({     // to support URL-encoded bodies
  extended: true
}));

app.use(express.static(__dirname + '/static'));

app.get('/',function(req,res){
	res.sendFile( __dirname + "/" + 'index.html');
});

app.post('/compress',function(req,res){
	console.log(req.body);
});

app.listen(port_no, function(){
	console.log("Express Started on Port "+port_no);
});

//var content = '<p title="blah" id="" id="moo" id="moo">  foo   </p> <h1> hi <!-- hi -->';
/*var content = '<html><head><title>Page Title</title></head><body><h1>This is a Heading</h1><p>This is a paragraph.</p></body></html>'
var result = minify(content, {
collapseWhitespace : true,
removeComments: true,
removeEmptyAttributes: true,
removeEmptyElements: true,

removeRedundantAttributes: true,
sortAttributes: true,
sortClassName: true,
removeComments: true,
minifyCSS: true,
minifyJS: true,
caseSensitive: true,
collapseInlineTagWhitespace: true,
keepClosingSlash: true,
includeAutoGeneratedTags: true
});
console.log(result);*/